### ISSUE TITLE
Accommodating NA values conditional on a categorical variable

### ISSUE THREAD

**Issue by rbcavanaugh** [m-Py/anticlust#49] opened 2023-06-22 13:05 UTC
Thanks for a great package - it has been fantastic for balancing stimuli sets in complex experiments. I was wondering if there's any way to include a variable with NA values conditional on a categorical variable. At the moment NA values are not permitted (understandable). Something like: 

```
library(tidyverse)
library(anticlust)
df <- mtcars |> 
  mutate(hp = ifelse(vs == 0, NA, hp)) |> 
  select(mpg, disp, hp, vs)

anticlustering(
  df[,1:3],
  K = c(9, 9, 9, 5),
  objective = "variance",
  categories = df$vs
)
```

Right now, my best idea is to do the clustering separately for each category (in this case, each level of `hp`) and then combine the data into the final groups, but I was wondering if there are any other ways. 

Cheers -

**Comment by m-Py** [comment] 2023-06-22 13:59
Thanks for your kind words!

Ah, `NA`s, my old nemesis. I am really unsure how to deal with them in `anticlust` because I feel I cannot decide for users how to deal with them. Actually, I allowed `NA`s in early versions of `anticlust`, but the problem is that it leads to undocumented and unclear behaviour (which probably was not "bad" for end users, but I found it highly dissatisfying on a theoretical level).

If you use the default diversity objective, you may rely on `dist()` magically dealing with the `NA`s for you (usually I would recommend the diversity over "variance" anyway, at least for equal-sized groups, which you do not have here):

```R
anticlustering(
  dist(df[,1:3]),
  K = c(9, 9, 9, 5)
)
```

Check out `?dist` on information how `NA`s are handled here.

By the way: Using your example, I also found a bug in `anticlust`, because the following code made `anticlustering() run into an infinite loop:

```R
anticlustering(
  dist(df[,1:3]),
  K = c(9, 9, 9, 5),
  categories = df$vs 
)
```

I know what caused this, though. Balancing categorical variables (with different class member frequencies) across uneven groups is quite hard and apparently, the current implementation did not deal with this constellation of groups.  Because I am currently working on the package anyway, I committed a [fix](https://github.com/m-Py/anticlust/commit/435958a0577) for this directly into the master branch on Github.

So, if you install the current version of anticlust from Github, the code runs.

```R
library("remotes") # if not available: install.packages("remotes")
install_github("m-Py/anticlust")
```

So, using the fixed package, I would use the following and then assess if this solution is good (which I cannot do here):

```R
groups <- anticlustering(
  dist(scale(df[,1:3])),#use standardization
  K = c(9, 9, 9, 5),
  categories = df$vs,
  method = "local-maximum", # better algorithm
  repetitions = 100 # repeat algorithm
)
mean_sd_tab(df[, 1:3], groups, na.rm = TRUE)
     mpg               disp                 hp             
#< 1 "20.50 (6.94)" "230.33 (141.15)" " 89.40 (31.20)"
#> 2 "20.03 (6.62)" "235.37 (144.74)" " 91.00 (29.43)"
#> 3 "20.38 (6.58)" "230.24 (125.62)" " 89.33 (22.72)"
#> 4 "18.94 (2.93)" "223.92 ( 75.06)" "100.00 ( 7.07)"
# seems okay to me. But I have no idea if this is good here.
```

What do you think? I am honestly open to suggestions. With the data you provide, I think it is quite difficult to assess the quality of any solution, because splitting 32 elements having 4 variables into 4 groups is a quite difficult task. I assume your "real" data looks different? Note that in general the default diversity objective does not always deal well with unequal group sizes. So we might use the kplus objective (which does not lead to different variances in different-sized groups); here I use mean imputation:

```R
copy <- df[, 1:3]
copy$hp[is.na(copy$hp)] <- mean(copy$hp, na.rm =TRUE)
groups <- anticlustering(
  copy, #use standardization
  K = c(9, 9, 9, 5),
  objective = "kplus",
  standardize = TRUE,
  method = "local-maximum",
  repetitions = 100,
  categories = df$vs
)

mean_sd_tab(df[, 1:3], groups, na.rm = TRUE)
#> 1 "19.98 (6.14)" "232.27 (129.33)" "91.50 (27.21)"
#> 2 "19.93 (6.28)" "233.16 (127.25)" "91.40 (25.03)"
#> 3 "19.94 (6.40)" "229.61 (128.06)" "93.67 (29.01)"
#> 4 "20.84 (6.66)" "225.56 (142.66)" "87.50 (36.06)"
```

Is this okay?

Another approach would indeed be to do the anticlustering two times and then merge the results. But I am not sure which option is better in your case without knowing the actual data.

**Comment by m-Py** [comment] 2023-06-22 14:09
I guess any sort of (advanced) data imputation scheme can be used, and mean imputation as far as I know is the worst. I have not done this myself, but I think combining data imputation with anticlustering is reasonable if `NA`s are present...

**Comment by rbcavanaugh** [comment] 2023-06-22 14:33
Thanks for the quick response! I can provide some actual data and details if that's helpful, but this is helpful in understanding a bit more of what's going on under the hood. 

In this case we have two outcome measures (a naming task and a discourse task...) where only a subset of words apply to both outcome measures. Here's some data that is fairly close to what I'm working with. In this case, `in_discourse` is a categorical variable that describes whether the stimuli (word) is used in the naming _and_ discourse outcome measure. `core_lex_percent`  is a measure from some norming we've done on our discourse measure that we want to balance on - but it only applies to stimuli that are relevant to the discourse task.

So I think the code to run it all in one go would look something like:

```
library(anticlust)
library(devtools)

dat <-  devtools::source_gist("d155e04609ede056428004ae460dbc4b")$value

dat$group <- anticlustering(
  dist(scale(dat[, c(4:6)])), 
  K = c(40, 40, 40, 60),
  method = "local-maximum",
  categories = dat$in_discourse,
  repetitions = 100,
  objective = "kplus",
  standardize = TRUE
)
```

This will run initially for me (no NA errors), but eventually errors out: 

```
Error in matrix(r, nrow = len.r, ncol = count) : 
  invalid 'ncol' value (too large or NA)
In addition: Warning message:
In combn(x, 2) : NAs introduced by coercion to integer range
```

I know this might be pushing the boundaries of the scope of the package (no worries!) - we've gotten used to quick stimuli balancing because you've made it so easy and I'm very grateful for that.

**Comment by m-Py** [comment] 2023-06-22 14:59
Yeah, sorry, your error is still caused by anticlust not being able to deal with your combination of `K` and `categories`. [I hope this is now finally fixed](https://github.com/m-Py/anticlust/commit/9bb8275cad).

So, again install the most recent version from Github to make the following code run. 

Here is your code with a slight change (not using a distance matrix as input):

```R

library(anticlust)
library(devtools)

dat <-  devtools::source_gist("d155e04609ede056428004ae460dbc4b")$value # wow, magic

# Mean imputation:
copy <- dat
copy$core_lex_percent[is.na(copy$core_lex_percent)] <- mean(copy$core_lex_percent, na.rm = TRUE)

groups <- anticlustering(
  copy[, 4:6], # use the variables directly
  K = c(40, 40, 40, 60),
  method = "local-maximum",
  categories = copy$in_discourse,
  repetitions = 100,
  objective = "kplus",
  standardize = TRUE
)

dat$group <- groups

# validat on original data (not imputed):
mean_sd_tab(dat[, 4:6], dat$group, na.rm = TRUE)
  agreement      item_difficulty core_lex_percent
#> 1 "90.44 (9.07)" "-0.06 (0.73)"  "51.04 (15.90)" 
#> 2 "90.43 (9.06)" "-0.06 (0.73)"  "51.04 (15.90)" 
#> 3 "90.40 (9.06)" "-0.06 (0.73)"  "50.87 (15.89)" 
#> 4 "90.42 (9.03)" "-0.06 (0.72)"  "51.08 (16.03)" 

table(dat$group, dat$in_discourse)
     0  1
  1 22 18
  2 22 18
  3 22 18
  4 34 26
```

I think the results are quite good. In this case, you cannot combine the distance matrix as input with the objective = "kplus", which requires the variables themselves (I think you would have gotten an error message if you had not run into the infinite loop... this should not be possible).

Anyway, thanks for reaching out. Without user feedback I will never find bugs as shown here myself. I also hope the solution is adequate for you.

**Comment by rbcavanaugh** [comment] 2023-06-23 00:11
Amazing - thanks so much. I agree - the lists end up incredibly balanced. I can't ask for much better than this. Cheers!

**Comment by m-Py** [comment] 2023-06-23 07:31
All right, I'm glad that it worked for you. If any preprint / publication results from this project, please let me know. I am always interested in `anticlust` applications.

**Closed by m-Py** 2023-06-23 07:31 UTC
Labels: bug

**Comment by rbcavanaugh** [comment] 2024-04-18 03:02
This is a long-standing follow-up and a question more than anything else. Within the category balancing, is there a way to set a minimum number of items per assignment? So imagine we had this kind of clustering with two groups dissimilar in size: 

```
groups <- anticlustering(
  copy[, 4:6], # use the variables directly
  K = c(150, 30),
  method = "local-maximum",
  categories = copy$in_discourse,
  repetitions = 100,
  objective = "kplus",
  standardize = TRUE
)
```

The current methods seem to make sure that the ratio of in_discourse is similar between the K groups (very sensible), but this can result in very small assignments for a K=30 group. So let's say we wanted to balance copy$in_discourse BUT we wanted to set a minimum of 10 items per in_disourse strata for both K groups. 

Not sure this is possible or perhaps a custom function for objective could allow this? Thanks again -

**Comment by m-Py** [comment] 2024-04-18 10:37
Hi Rob,

there is no way to do that with one call to `anticlustering()`, which assumes that categorical variables are similar between sets when the proportions of each class is similar in each set.

In your case, I would try out to do two `anticlustering()` calls (assuming there are two levels in `copy$in_discourse`), one for each value in `copy$in_discourse`, and the merge the groups. 

So I guess something like this:

```R

in_discourse1 <- copy[copy$in_discourse == "value1", ]
in_discourse2 <- copy[copy$in_discourse == "value2", ]

groups1 <- anticlustering(
  in_discourse1[, 4:6], 
  K = c(140, 20),
  method = "local-maximum",
  repetitions = 100,
  objective = "kplus",
  standardize = TRUE
)

groups2 <- anticlustering(
  in_discourse1[, 4:6], 
  K = c(10, 10), # not sure which number add up
  method = "local-maximum",
  repetitions = 100,
  objective = "kplus",
  standardize = TRUE
)

```

Does this work for you? I assume the two sets should be similar overall and you obtain the required numbers in each group.

**Comment by m-Py** [comment] 2024-04-18 10:39
I assume you could also write a custom objective function, but this would require some additional thought I guess.

**Comment by m-Py** [comment] 2024-04-18 11:31
Glad this helps!  Good luck with your work.
